apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  selector:
    matchLabels:
      app: react-frontend-deployment
  template:
    metadata:
      labels:
        app: react-frontend-deployment
    spec:
      containers:
      - name: react-frontend-deployment
        image: architdev/react-frontend:0.1
        ports:
        - containerPort: 3000
